// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdvaiujlorzomlzrtdaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdmFpdWpsb3J6b21senJ0ZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODc4NTEsImV4cCI6MjA3MDQ2Mzg1MX0.Fl0w5FMBTxqMHTja6AkCpjMCLZ8ERgM1DuSx1AJpNkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});